<a href="https://colab.research.google.com/github/MarvinAntillon97/etl-data-pipeline/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"

df = pd.read_csv(url)

df.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [3]:
#Limpieza de datos
clientes = df.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
    clientes[col] = clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

clientes['email'] = clientes['email'].str.lower()

clientes['fecha_nacimiento'] = pd.to_datetime(clientes['fecha_nacimiento'], errors='coerce')

clientes = clientes.drop_duplicates()

In [4]:
#Separar datos validos y rechazados
validos = clientes[
    clientes['nombre'].notna() &
    clientes['email'].notna()
].copy()

rechazados = clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

In [5]:
#motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [6]:
#Exportar archivos

validos.to_csv("clientes_curated.csv", index=False)

rechazados.to_csv("clientes_rejects.csv", index=False)

In [7]:
#Conectar con PostGresql
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_ad3f_user:dfCEzp79Czz4SFMCXmINhlJs1gBDNT9G@dpg-d6qu7s450q8c73bpf58g-a.oregon-postgres.render.com/etl_seguros_ad3f"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 36.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [8]:
validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [9]:
pd.read_sql(
"SELECT fecha_nacimiento FROM clientes_curated LIMIT 10",
engine
)

  fecha_nacimiento
0       2011-11-24
1              NaT
2              NaT
3              NaT
4       1945-08-02
5       1966-10-15
6              NaT
7              NaT
8              NaT
9              NaT

BLOQUE DE ASEGURADORAS

In [10]:
url_aseguradoras = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/aseguradoras.csv"

aseguradoras = pd.read_csv(url_aseguradoras)

aseguradoras.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [12]:
# Limpieza de datos aseguradoras

aseguradoras = aseguradoras.copy()

# Normalizar columnas
aseguradoras.columns = aseguradoras.columns.str.strip().str.lower()

# Limpiar espacios en texto
for col in aseguradoras.select_dtypes(include='object').columns:
    aseguradoras[col] = aseguradoras[col].astype(str).str.strip()

# Reemplazar vacíos por NaN
aseguradoras = aseguradoras.replace(r'^\s*$', pd.NA, regex=True)

# ==============================
# MEJORAS DE CALIDAD DE DATOS
# ==============================

# Limpiar nombres
aseguradoras['nombre'] = aseguradoras['nombre'].str.title()

# Limpiar país
aseguradoras['pais'] = aseguradoras['pais'].str.replace("ElSalvador", "El Salvador")
aseguradoras['pais'] = aseguradoras['pais'].str.title()

# Limpiar rating_riesgo
map_rating = {
    "alto": "Alto",
    "medio": "Medio",
    "bajo": "Bajo",
    "b": "Bajo"
}

aseguradoras['rating_riesgo'] = aseguradoras['rating_riesgo'].str.lower().map(map_rating)

aseguradoras['rating_riesgo'] = aseguradoras['rating_riesgo'].fillna("No especificado")

In [13]:
aseguradoras.head()

   id_aseguradora         nombre         pais    rating_riesgo
0               1  Aseguradora 1   Costa Rica             Alto
1               2  Aseguradora 2  El Salvador             Bajo
2               3  Aseguradora 3  El Salvador  No especificado
3               4  Aseguradora 4   Costa Rica            Medio
4               5  Aseguradora 5  El Salvador             Bajo

In [14]:
aseguradoras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            15 non-null     object
 3   rating_riesgo   15 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

In [15]:
aseguradoras.isnull().sum()

id_aseguradora    0
nombre            0
pais              0
rating_riesgo     0
dtype: int64

In [16]:
# Separar datos aseguradoras

aseguradoras_validos = aseguradoras.copy()

In [18]:
# Crear rejects vacío (misma estructura)

aseguradoras_rechazados = aseguradoras[0:0]

# Exportar archivos

aseguradoras_validos.to_csv("aseguradoras_curated.csv", index=False)
aseguradoras_rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [19]:
# Subir a base de datos

aseguradoras_validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

aseguradoras_rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [20]:
pd.read_sql("SELECT * FROM aseguradoras_curated LIMIT 5", engine)

   id_aseguradora         nombre         pais    rating_riesgo
0               1  Aseguradora 1   Costa Rica             Alto
1               2  Aseguradora 2  El Salvador             Bajo
2               3  Aseguradora 3  El Salvador  No especificado
3               4  Aseguradora 4   Costa Rica            Medio
4               5  Aseguradora 5  El Salvador             Bajo

BLOQUE CORREDORES

In [22]:
# ==============================
# CORREDORES
# ==============================

url_corredores = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/corredores.csv"

corredores = pd.read_csv(url_corredores)

corredores.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [24]:
# Limpieza básica corredores

corredores = corredores.copy()

# Normalizar columnas
corredores.columns = corredores.columns.str.strip().str.lower()

# Limpiar espacios
for col in corredores.select_dtypes(include='object').columns:
    corredores[col] = corredores[col].astype(str).str.strip()

# Reemplazar vacíos por NaN
corredores = corredores.replace(r'^\s*$', pd.NA, regex=True)

In [25]:
# Mejoras de calidad

# Nombre
corredores['nombre'] = corredores['nombre'].str.title()

# Zona (aquí tienes nulos)
corredores['zona'] = corredores['zona'].str.title()
corredores['zona'] = corredores['zona'].fillna("No especificado")

# Nivel (CLAVE)
map_nivel = {
    "junior": "Junior",
    "mid": "Mid",
    "senior": "Senior"
}

corredores['nivel'] = corredores['nivel'].str.lower().map(map_nivel)
corredores['nivel'] = corredores['nivel'].fillna("No especificado")

# Años de experiencia
corredores['anios_experiencia'] = pd.to_numeric(
    corredores['anios_experiencia'], errors='coerce'
)

In [26]:
corredores.head()

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  Senior                6.0
3            4  Fernanda Rojas Cruz          Nan  Senior                8.0
4            5      Ana Gómez Rojas          Nan  Senior                4.0

In [27]:
corredores.isnull().sum()

id_corredor          0
nombre               0
zona                 0
nivel                0
anios_experiencia    4
dtype: int64

In [28]:
# Separar datos válidos y rechazados

corredores_validos = corredores[
    corredores['anios_experiencia'].notna()
].copy()

corredores_rechazados = corredores[
    corredores['anios_experiencia'].isna()
].copy()

In [29]:
# Motivo de rechazo

def motivo(row):
    motivos = []

    if pd.isna(row['anios_experiencia']):
        motivos.append("experiencia_vacia")

    return ",".join(motivos)

corredores_rechazados["motivo_rechazo"] = corredores_rechazados.apply(motivo, axis=1)

In [30]:
corredores_validos.to_csv("corredores_curated.csv", index=False)
corredores_rechazados.to_csv("corredores_rejects.csv", index=False)

In [31]:
corredores_validos.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

corredores_rechazados.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

4

In [32]:
pd.read_sql("SELECT * FROM corredores_rejects", engine)

,id_corredor,nombre,zona,nivel,anios_experiencia,motivo_rechazo
0,11,José Morales Flores,Nan,Junior,None,experiencia_vacia
1,15,Fernanda Cruz Reyes,Centro,Mid,None,experiencia_vacia
2,61,Carlos Torres Mendoza,Centro,Junior,None,experiencia_vacia
3,77,Valeria Vásquez Mendoza,Centro,Junior,None,experiencia_vacia